### ISSUE TITLE
Question: System Requirements

### ISSUE THREAD

**Issue by sundarv85** [sitespeedio/coach#330]
Great project! One point we noted is: when we run this on a dual core + 4GB RAM - the performance is different than when compared to running it on CPU Optimized Quad Core + 4GB RAM.

The reason, of course, is that the Google Chrome is efficiently using the CPU optimized quad core for loading the resources in parallel, which drastically reduces the time consumed. 

The question we have is: 

1. What are the recommended system requirements
2. Even if we move to a high performance system, is there a way to limit webcoach/browsertime to use a limited CPU/Memory so that the output of performance can always be consistent within itself.

**Comment by soulgalore** [comment]
Hi @sundarv85 
do you mean performance like how fast you get the result back from the coach or the actual performance score you get?

The performance score is independent of the machine you use it looks at how the page are build and not on actual numbers like first paint etc. The metrics is only collected by the coach but not used by calculating the score since these kind of metrics depends on CPU, memory, what kind of connectivity etc. So if you run sitespeed.io or Browsertime continuously and act on performance metrics you need test and find out what kind instance size that works for you: faster instance usually gives more stable metrics. But then since the CPU is faster, it will be harder to see regressions.

If you limit resources that easiest done on OS level. If you run using Docker, Docker have some ways of limit resource usage.

Best
Peter

**Comment by sundarv85** [comment]
Hi @soulgalore 

I meant the actual resource limitation (the performance metrics from the pages itself). Thanks. We will explore further on Docker and resource limitations.. Thanks for the quick response!
